export const repeatData = {
    'timestamp': 1516239853245,
    'code': 200,
    'message': '请求成功',
    'exception': null,
    'data': {
      'draw': 0,
      'start': 0,
      'length': 10,
      'recordsTotal': 3395,
      'resultObject': [
        {
          'id': '5a5eac9f8c9bebe5e836fcff',
          'firstLevelCategoryName': '粮油副食',
          'secondLevelCategoryName': '粮食类',
          'thirdLevelCategoryName': '奶粉/辅食',
          'fourthLevelCategoryName': '长粒香',
          'brand': '金龙鱼',
          'productCode': '1000042',
          'productName': '金龙鱼清香稻5KG',
          'branchCompanyId': '10000',
          'branchCompanyName': '成都子公司',
          'storeCode': 'A000001',
          'storeName': '鑫莉超市16',
          'supplierCode': 'xxxx_sup',
          'supplierName': 'xx供应商',
          'adrSupCode': 'xxxx_adr',
          'adrSupName': 'xx地点',
          'logisticsModel': null
        },
        {
          'id': '5a5eac9f8c9bebe5e836fd00',
          'firstLevelCategoryName': '粮油副食',
          'secondLevelCategoryName': '粮食类',
          'thirdLevelCategoryName': '奶粉/辅食',
          'fourthLevelCategoryName': '长粒香',
          'brand': '金龙鱼',
          'productCode': '1000042',
          'productName': '金龙鱼清香稻5KG',
          'branchCompanyId': '10000',
          'branchCompanyName': '成都子公司',
          'storeCode': 'A000029',
          'storeName': '兴鑫烟酒副食品商行',
          'supplierCode': 'xxxx_sup',
          'supplierName': 'xx供应商',
          'adrSupCode': 'xxxx_adr',
          'adrSupName': 'xx地点',
          'logisticsModel': null
        },
        {
          'id': '5a5eac9f8c9bebe5e836fd01',
          'firstLevelCategoryName': '粮油副食',
          'secondLevelCategoryName': '粮食类',
          'thirdLevelCategoryName': '奶粉/辅食',
          'fourthLevelCategoryName': '长粒香',
          'brand': '金龙鱼',
          'productCode': '1000042',
          'productName': '金龙鱼清香稻5KG',
          'branchCompanyId': '10000',
          'branchCompanyName': '成都子公司',
          'storeCode': 'A000030',
          'storeName': '雨露干杂铺',
          'supplierCode': 'xxxx_sup',
          'supplierName': 'xx供应商',
          'adrSupCode': 'xxxx_adr',
          'adrSupName': 'xx地点',
          'logisticsModel': null
        },
        {
          'id': '5a5eac9f8c9bebe5e836fd04',
          'firstLevelCategoryName': '粮油副食',
          'secondLevelCategoryName': '粮食类',
          'thirdLevelCategoryName': '奶粉/辅食',
          'fourthLevelCategoryName': '长粒香',
          'brand': '金龙鱼',
          'productCode': '1000042',
          'productName': '金龙鱼清香稻5KG',
          'branchCompanyId': '10000',
          'branchCompanyName': '成都子公司',
          'storeCode': 'A000069',
          'storeName': '他她士多超市',
          'supplierCode': null,
          'supplierName': null,
          'adrSupCode': null,
          'adrSupName': null,
          'logisticsModel': 1
        },
        {
          'id': '5a5eac9f8c9bebe5e836fd05',
          'firstLevelCategoryName': '粮油副食',
          'secondLevelCategoryName': '粮食类',
          'thirdLevelCategoryName': '奶粉/辅食',
          'fourthLevelCategoryName': '长粒香',
          'brand': '金龙鱼',
          'productCode': '1000042',
          'productName': '金龙鱼清香稻5KG',
          'branchCompanyId': '10000',
          'branchCompanyName': '成都子公司',
          'storeCode': 'A000079',
          'storeName': '易惠便利超市',
          'supplierCode': 'xxxx_sup',
          'supplierName': 'xx供应商',
          'adrSupCode': 'xxxx_adr',
          'adrSupName': 'xx地点',
          'logisticsModel': null
        },
        {
          'id': '5a5eac9f8c9bebe5e836fd06',
          'firstLevelCategoryName': '粮油副食',
          'secondLevelCategoryName': '粮食类',
          'thirdLevelCategoryName': '奶粉/辅食',
          'fourthLevelCategoryName': '长粒香',
          'brand': '金龙鱼',
          'productCode': '1000042',
          'productName': '金龙鱼清香稻5KG',
          'branchCompanyId': '10000',
          'branchCompanyName': '成都子公司',
          'storeCode': 'A000090',
          'storeName': '生活区便利店',
          'supplierCode': 'xxxx_sup',
          'supplierName': 'xx供应商',
          'adrSupCode': 'xxxx_adr',
          'adrSupName': 'xx地点',
          'logisticsModel': null
        },
        {
          'id': '5a5eac9f8c9bebe5e836fd07',
          'firstLevelCategoryName': '粮油副食',
          'secondLevelCategoryName': '粮食类',
          'thirdLevelCategoryName': '奶粉/辅食',
          'fourthLevelCategoryName': '长粒香',
          'brand': '金龙鱼',
          'productCode': '1000042',
          'productName': '金龙鱼清香稻5KG',
          'branchCompanyId': '10000',
          'branchCompanyName': '成都子公司',
          'storeCode': 'A000092',
          'storeName': '高新区幸福购便利店',
          'supplierCode': 'xxxx_sup',
          'supplierName': 'xx供应商',
          'adrSupCode': 'xxxx_adr',
          'adrSupName': 'xx地点',
          'logisticsModel': null
        },
        {
          'id': '5a5eac9f8c9bebe5e836fd08',
          'firstLevelCategoryName': '粮油副食',
          'secondLevelCategoryName': '粮食类',
          'thirdLevelCategoryName': '奶粉/辅食',
          'fourthLevelCategoryName': '长粒香',
          'brand': '金龙鱼',
          'productCode': '1000042',
          'productName': '金龙鱼清香稻5KG',
          'branchCompanyId': '10000',
          'branchCompanyName': '成都子公司',
          'storeCode': 'A000093',
          'storeName': '雷雨便利店',
          'supplierCode': 'xxxx_sup',
          'supplierName': 'xx供应商',
          'adrSupCode': 'xxxx_adr',
          'adrSupName': 'xx地点',
          'logisticsModel': null
        },
        {
          'id': '5a5eac9f8c9bebe5e836fd09',
          'firstLevelCategoryName': '粮油副食',
          'secondLevelCategoryName': '粮食类',
          'thirdLevelCategoryName': '奶粉/辅食',
          'fourthLevelCategoryName': '长粒香',
          'brand': '金龙鱼',
          'productCode': '1000042',
          'productName': '金龙鱼清香稻5KG',
          'branchCompanyId': '10000',
          'branchCompanyName': '成都子公司',
          'storeCode': 'A000094',
          'storeName': '温江实在超市1111111',
          'supplierCode': null,
          'supplierName': null,
          'adrSupCode': null,
          'adrSupName': null,
          'logisticsModel': 1
        },
        {
          'id': '5a5eac9f8c9bebe5e836fd0a',
          'firstLevelCategoryName': '粮油副食',
          'secondLevelCategoryName': '粮食类',
          'thirdLevelCategoryName': '奶粉/辅食',
          'fourthLevelCategoryName': '长粒香',
          'brand': '金龙鱼',
          'productCode': '1000042',
          'productName': '金龙鱼清香稻5KG',
          'branchCompanyId': '10000',
          'branchCompanyName': '成都子公司',
          'storeCode': 'A000095',
          'storeName': '兰姐副食www',
          'supplierCode': 'xxxx_sup',
          'supplierName': 'xx供应商',
          'adrSupCode': 'xxxx_adr',
          'adrSupName': 'xx地点',
          'logisticsModel': null
        },
        {
          'id': '5a5eac9f8c9bebe5e836fd0b',
          'firstLevelCategoryName': '粮油副食',
          'secondLevelCategoryName': '粮食类',
          'thirdLevelCategoryName': '奶粉/辅食',
          'fourthLevelCategoryName': '长粒香',
          'brand': '金龙鱼',
          'productCode': '1000042',
          'productName': '金龙鱼清香稻5KG',
          'branchCompanyId': '10000',
          'branchCompanyName': '成都子公司',
          'storeCode': 'A000097',
          'storeName': '祥益超市',
          'supplierCode': 'xxxx_sup',
          'supplierName': 'xx供应商',
          'adrSupCode': 'xxxx_adr',
          'adrSupName': 'xx地点',
          'logisticsModel': null
        },
        {
          'id': '5a5eac9f8c9bebe5e836fd0c',
          'firstLevelCategoryName': '粮油副食',
          'secondLevelCategoryName': '粮食类',
          'thirdLevelCategoryName': '奶粉/辅食',
          'fourthLevelCategoryName': '长粒香',
          'brand': '金龙鱼',
          'productCode': '1000042',
          'productName': '金龙鱼清香稻5KG',
          'branchCompanyId': '10000',
          'branchCompanyName': '成都子公司',
          'storeCode': 'A000098',
          'storeName': '吉佳副食超市',
          'supplierCode': null,
          'supplierName': null,
          'adrSupCode': null,
          'adrSupName': null,
          'logisticsModel': 1
        },
        {
          'id': '5a5eac9f8c9bebe5e836fd0d',
          'firstLevelCategoryName': '粮油副食',
          'secondLevelCategoryName': '粮食类',
          'thirdLevelCategoryName': '奶粉/辅食',
          'fourthLevelCategoryName': '长粒香',
          'brand': '金龙鱼',
          'productCode': '1000042',
          'productName': '金龙鱼清香稻5KG',
          'branchCompanyId': '10000',
          'branchCompanyName': '成都子公司',
          'storeCode': 'A000116',
          'storeName': '三林连锁超市（林红副食经营部',
          'supplierCode': 'xxxx_sup',
          'supplierName': 'xx供应商',
          'adrSupCode': 'xxxx_adr',
          'adrSupName': 'xx地点',
          'logisticsModel': null
        },
        {
          'id': '5a5eac9f8c9bebe5e836fd0e',
          'firstLevelCategoryName': '粮油副食',
          'secondLevelCategoryName': '粮食类',
          'thirdLevelCategoryName': '奶粉/辅食',
          'fourthLevelCategoryName': '长粒香',
          'brand': '金龙鱼',
          'productCode': '1000042',
          'productName': '金龙鱼清香稻5KG',
          'branchCompanyId': '10000',
          'branchCompanyName': '成都子公司',
          'storeCode': 'A000118',
          'storeName': '万惠副食',
          'supplierCode': 'xxxx_sup',
          'supplierName': 'xx供应商',
          'adrSupCode': 'xxxx_adr',
          'adrSupName': 'xx地点',
          'logisticsModel': null
        },
        {
          'id': '5a5eac9f8c9bebe5e836fd0f',
          'firstLevelCategoryName': '粮油副食',
          'secondLevelCategoryName': '粮食类',
          'thirdLevelCategoryName': '奶粉/辅食',
          'fourthLevelCategoryName': '长粒香',
          'brand': '金龙鱼',
          'productCode': '1000042',
          'productName': '金龙鱼清香稻5KG',
          'branchCompanyId': '10000',
          'branchCompanyName': '成都子公司',
          'storeCode': 'A000120',
          'storeName': '众悦日用品经营部',
          'supplierCode': 'xxxx_sup',
          'supplierName': 'xx供应商',
          'adrSupCode': 'xxxx_adr',
          'adrSupName': 'xx地点',
          'logisticsModel': null
        }
      ],
      'currentPage': 1
    },
    'success': true
  }
  